apiVersion: v1
kind: Service
metadata:
  name: first-simple-express
  labels:
    run: first-simple-express
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: first-simple-express
